### ISSUE TITLE
No sound when playing on client web browser 

### ISSUE THREAD

**Issue by Tazintosh** [owntone/owntone-container#11]
Hi there (and Happy New Year!)

I'm using Docker (OrbStack) on a Mac mini M1 running Sequoia 15.2
I've created a composer file to run OwnTone like so:
```
  name: OwnTone
  services:
    owntone:
      image: docker.io/owntone/owntone:latest
      container_name: OwnTone
      restart: on-failure:5
      environment:
        - UID="501"
        - GID="staff"
        - TZ="Europe/Paris"
      volumes:
        - /Users/myUser/Documents/Docker/OwnTone/etc:/etc/owntone:rw
        - /Users/myUser/Documents/Docker/OwnTone/cache:/var/cache/owntone:rw
        - /Volumes/Storage/Media/Music/Music Media/Test:/srv/media:ro
      network_mode: "host"
```

I can successfully connect to the web UI from a client computer (another Mac mini M1) but while the track is playing, I've no audio.
When clicking the lower right "chevron" I can see the following:

- Volume slider is available
- Server slider is greyed out
- Computer slider is greyed out

When I click on the server icon, I getting the following error: `La requête a échoué (status: 400 Bad Request http://sub.mydomain.com:3689/api/outputs/213952590763332)`
When I click on the computer icon, I getting the following error: `La requête a échoué (status: 400 Bad Request http://sub.mydomain.com:3689/api/outputs/0))`
When I click the HTTP flux, it works.

Is this expected?
Thanks in advance
